language: php

group: deprecated-2017Q4

php:
  - '5.6'
  - '7.0'

services:
  - docker

env:
  global:
    - VENDOR_DIR=wp-content/plugins/bliskapaczka-shipping-method/vendor
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - composer install
  - $VENDOR_DIR/bin/phpcs --config-set installed_paths ../../wp-coding-standards/wpcs
  - $VENDOR_DIR/bin/phpcs -s --colors --standard=WordPress wp-content/plugins/bliskapaczka-shipping-method/class-bliskapaczka-shipping-method.php
  - $VENDOR_DIR/bin/phpcpd wp-content/plugins/bliskapaczka-shipping-method/class-bliskapaczka-shipping-method.php
  - $VENDOR_DIR/bin/phploc wp-content/plugins/bliskapaczka-shipping-method/class-bliskapaczka-shipping-method.php
  - $VENDOR_DIR/bin/phpunit --bootstrap wp-content/plugins/bliskapaczka-shipping-method/tests/bootstrap.php wp-content/plugins/bliskapaczka-shipping-method/tests/unit/

jobs:
  include:
    - stage: build
      script: 
        - docker build -t bliskapaczkapl/woocommerce:$COMMIT -t bliskapaczkapl/woocommerce:latest -t bliskapaczkapl/woocommerce:develop .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push bliskapaczkapl/woocommerce:$COMMIT
        - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker push bliskapaczkapl/woocommerce:latest;
          fi
        - if [ "$TRAVIS_BRANCH" == "develop" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker push bliskapaczkapl/woocommerce:develop;
          fi
      php: 7.0
